import mongoose from 'mongoose';

/**
 * Early Warning Alert Model
 * Generated by AI agents when high delinquency probability or unusual anomalies occur.
 */
const alertSchema = new mongoose.Schema(
  {
    alertId: {
      type: String,
      required: true,
      unique: true
    },
    customerId: {
      type: String,
      required: true,
      ref: 'Customer'
    },
    severity: {
      type: String,
      enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
      default: 'MEDIUM'
    },
    triggerSource: {
      type: String,
      enum: ['PAYMENT_DELAY', 'CASH_DRAIN', 'NLP_COMPLAINT', 'ANOMALY_DETECTION'],
      required: true
    },
    narrative: String,
    suggestedAction: String,
    status: {
      type: String,
      enum: ['OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED'],
      default: 'OPEN'
    }
  },
  {
    timestamps: true
  }
);

export default mongoose.models.Alert || mongoose.model('Alert', alertSchema);
